apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notebook-on-kube.fullname" . }}
  labels:
    {{- include "notebook-on-kube.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "notebook-on-kube.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "notebook-on-kube.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.Version) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NOK_NAMESPACE
              value: {{ .Release.Namespace }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.notebookDefaultValues }}
          volumeMounts:
            - name: values
              mountPath: "/app/chart/jupyter-notebook"
              # Does not receive changes.
              subPath: "values.yaml"
              readOnly: true
      volumes:
        - name: values
          secret:
            secretName: {{ include "notebook-on-kube.fullname" . }}-notebook-default-values
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
