kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "notebook-on-kube.fullname" . }}
  labels:
    {{- include "notebook-on-kube.labels" . | nindent 4 }}
spec:
  ingressClassName: notebook-on-kube
  rules:
  - http:
      paths:
      - pathType: Exact
        path: /
        backend:
          service:
            name: {{ include "notebook-on-kube.fullname" . }}
            port:
              name: http
      - pathType: Exact
        path: /favicon.ico
        backend:
          service:
            name: {{ include "notebook-on-kube.fullname" . }}
            port:
              name: http
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: {{ include "notebook-on-kube.fullname" . }}
            port:
              name: http
