{{- if .Values.notebookDefaultValues }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ include "notebook-on-kube.fullname" . }}-notebook-default-values
  labels:
    {{- include "notebook-on-kube.labels" . | nindent 4 }}
stringData:
  values.yaml: |
{{ toYaml .Values.notebookDefaultValues | indent 4 }}

{{- end }}
