kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "jupyter-notebook.fullname" . }}
  labels:
    {{- include "jupyter-notebook.labels" . | nindent 4 }}
spec:
  ingressClassName: notebook-on-kube
  rules:
  - http:
      paths:
      - pathType: Prefix
        # No real auth on this
        path: /connect_notebook/{{ include "jupyter-notebook.fullname" . }}
        backend:
          service:
            name: {{ include "jupyter-notebook.fullname" . }}
            port:
              name: http