{{- if .Values.extraSecretEnv }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyter-notebook.fullname" . }}
  labels:
    {{- include "jupyter-notebook.labels" . | nindent 4 }}
stringData:
{{ toYaml .Values.extraSecretEnv | indent 2 }}

{{- end }}
